=== PazmanAndras/H2Z4X3_XMLGyak/XMLTaskH2Z4X3/XMLSchemah2z4x3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- Egyszerű típusok kigyűjtése, saját típusok meghatározása  -->
    <xs:element name="kapacitás" type="xs:integer" />
    <xs:element name="minősítés" type="minősítésTipus" />
    <xs:element name="név" type="xs:string" />
    <xs:element name="cim" type="xs:string" />
    <xs:element name="telszám" type="xs:string" />
    <xs:element name="adoszam" type="adószámTípus" />
    <xs:element name="bevétel" type="xs:integer" />
    <xs:element name="rendszám" type="rendszámTípus" />
    <xs:element name="modell" type="xs:string" />
    <xs:element name="alvázszám" type="alvázszámTípus" />
    <xs:element name="gyártásiév" type="xs:gYear" />
    <xs:element name="email" type="xs:string" />
    <xs:element name="jogositvanyszam" type="jogosítványszámTípus" />
    <xs:element name="beosztás" type="xs:string" />
    <xs:element name="életkor" type="xs:integer" />
    <xs:element name="születésiév" type="xs:gYear" />
    <xs:element name="extra" type="extraTipus" />
    <xs:element name="bizoszítványszám" type="bizoszítványszámTípus" />
    <xs:element name="év" type="xs:gYear" />
    <xs:element name="nyelv" type="xs:string" />
    <xs:element name="tipus" type="tipusTipus" />

    <xs:simpleType name="minősítésTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A" />
            <xs:enumeration value="B" />
            <xs:enumeration value="C" />
            <xs:enumeration value="D" />
            <xs:enumeration value="E" />        
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="adószámTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="(\d{8})-(\d)-(\d{2})" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="bevételTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="100000" />
            <xs:maxInclusive value="10000000" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="rendszámTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z]{3}-\d{3})" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="alvázszámTípus">
        <xs:restriction base="xs:string">
            <xs:length value="17" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="jogosítványszámTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z]{2}\d{6})" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="extraTipus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="10000" />
            <xs:maxInclusive value="50000" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipusTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1" />
            <xs:enumeration value="A2" />
            <xs:enumeration value="B1" />
            <xs:enumeration value="B2" />
            <xs:enumeration value="C1" />
            <xs:enumeration value="C2" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="bizoszítványszámTípus">
        <xs:restriction base="xs:string">
            <xs:length value="7" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Komplex típushoz sajat típus-->
    <xs:complexType name="telepTípus">
        <xs:sequence>
            <xs:element ref="kapacitás" />           
            <xs:element name="cim">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="település" type="xs:string" />
                        <xs:element name="utca" type="xs:string" />
                        <xs:element name="házszám" type="xs:integer" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="minősítés" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="TELEP_ID" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="tulajdonosTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="telszám" minOccurs="1" maxOccurs="unbounded" />
            <xs:element ref="adoszam" />
            <xs:element ref="bevétel" />
        </xs:sequence>
        <xs:attribute name="TUL_ID" type="xs:integer" use="required" />
        <xs:attribute name="TUL_TELEP" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="autokTípus">
        <xs:sequence>
            <xs:element ref="rendszám" />
            <xs:element ref="modell" minOccurs="1" maxOccurs="unbounded" />
            <xs:element ref="alvázszám" />
            <xs:element ref="gyártásiév" />           
        </xs:sequence>
        <xs:attribute name="AUTO_ID" type="xs:integer" use="required" />
        <xs:attribute name="AUTO_TELEP" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="bérlőTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="telszám" minOccurs="1" maxOccurs="unbounded" />
            <xs:element ref="email" />
            <xs:element ref="jogositvanyszam" />           
        </xs:sequence>
        <xs:attribute name="BÉRLŐ_ID" type="xs:integer" use="required" />
        <xs:attribute name="BÉRLŐ_AUTO" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="alkalmazottTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element ref="beosztás" minOccurs="1" maxOccurs="unbounded" />
            <xs:element ref="életkor" />
            <xs:element ref="születésiév" />           
        </xs:sequence>
        <xs:attribute name="ALK_ID" type="xs:integer" use="required" />
        <xs:attribute name="ALK_TELEP" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="képesítésTípus">
        <xs:sequence>
            <xs:element ref="bizoszítványszám" />
            <xs:element ref="év" /> 
            <xs:element ref="nyelv" />
            <xs:element ref="tipus" />           
        </xs:sequence>
        <xs:attribute name="KÉPESÍTÉS_ID" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="bónuszTípus">
        <xs:sequence>
            <xs:element ref="extra" />         
        </xs:sequence>
        <xs:attribute name="BONUSZ_ID" type="xs:integer" use="required" />
        <xs:attribute name="KÉPESÍTÉS_FK" type="xs:integer" use="required" />
        <xs:attribute name="ALKALMAZOTT_FK" type="xs:integer" use="required" />
    </xs:complexType>

     <!-- Gyökérelemtől az elemek felhasználása -->
     <xs:element name="H2Z4X3_autokolcsonzo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="telep" type="telepTípus" minOccurs="0" maxOccurs="10"/>
                <xs:element name="tulajdonos" type="tulajdonosTípus" minOccurs="0" maxOccurs="10"/>
                <xs:element name="autok" type="autokTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="bérlő" type="bérlőTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="alkalmazott" type="alkalmazottTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="bonusz" type="bónuszTípus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="képesítés" type="képesítésTípus" minOccurs="0" maxOccurs="50"/>
            </xs:sequence>
        </xs:complexType>

        <!-- Elsődleges kulcsok-->
        <xs:key name="telep_kulcs">
            <xs:selector xpath="telep"/>
            <xs:field xpath="@TELEP_ID"/>
        </xs:key>
        <xs:key name="tulajdonos_kulcs">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@TUL_ID"/>
        </xs:key>
        <xs:key name="autok_kulcs">
            <xs:selector xpath="fellépő"/>
            <xs:field xpath="@AUTO_ID"/>
        </xs:key>
        <xs:key name="bérlő_kulcs">
            <xs:selector xpath="bérlő"/>
            <xs:field xpath="@BÉRLŐ_ID"/>
        </xs:key>
        <xs:key name="alkalmazott_kulcs">
            <xs:selector xpath="alkalmazott"/>
            <xs:field xpath="@ALK_ID"/>
        </xs:key>
        <xs:key name="bonusz_kulcs">
            <xs:selector xpath="bonusz"/>
            <xs:field xpath="@BONUSZ_ID"/>
        </xs:key>
        <xs:key name="képsítés_kulcs">
            <xs:selector xpath="képesítés"/>
            <xs:field xpath="@KÉPESÍTÉS_ID"/>
        </xs:key>

        
        <!-- Idegen kulcsok-->

        <xs:keyref name="telep_tulajdonos_kulcs" refer="telep_kulcs">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@telep"/>
        </xs:keyref>
        <xs:keyref name="telep_autok_kulcs" refer="telep_kulcs">
            <xs:selector xpath="autok"/>
            <xs:field xpath="@telep"/>
        </xs:keyref>

        <xs:keyref name="telep_alkalmazott_kulcs" refer="telep_kulcs">
            <xs:selector xpath="alkalmazott"/>
            <xs:field xpath="@telep"/>
        </xs:keyref>
        <xs:keyref name="autok_bérlő_kulcs" refer="autok_kulcs">
            <xs:selector xpath="bérlő"/>
            <xs:field xpath="@autok"/>
        </xs:keyref>
        <xs:keyref name="alkalmazott_bonusz_kulcs" refer="alkalmazott_kulcs">
            <xs:selector xpath="bonusz"/>
            <xs:field xpath="@alkalmazott"/>
        </xs:keyref>
        <xs:keyref name="képesítés_bonusz_kulcs" refer="képsítés_kulcs">
            <xs:selector xpath="bonusz"/>
            <xs:field xpath="@képsítés"/>
        </xs:keyref>


        <!-- Az 1:1 kapcsolat megvalósítás -->
        <xs:unique name="telep_tulajdonos_egyegy">
            <xs:selector xpath="tulajdonos"/>
            <xs:field xpath="@ftelep"/>
        </xs:unique>
        <xs:unique name="autok_bérlő_egyegy">
            <xs:selector xpath="bérlő"/>
            <xs:field xpath="@autok"/>
        </xs:unique>


     </xs:element>


</xs:schema>

=== PazmanAndras/H2Z4X3_XMLGyak/XMLTaskH2Z4X3/domread/src/XMLh2z4x3.xml
<?xml version="1.0" encoding="UTF-8"?>


<H2Z4X3_autokolcsonzo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="XMLSchemah2z4x3.xsd">
    
    <!-- TELEP -->
    <telep TELEP_ID = "1">
        <kapacitás>5</kapacitás>  
        <cim>
            <település>Budapest</település>
            <utca>Benczúr_utca</utca>
            <házszám>23</házszám>
       </cim>
       <minősítés>B</minősítés>
    </telep>

    <telep TELEP_ID = "2">
        <kapacitás>8</kapacitás>  
        <cim>
            <település>Budapest</település>
            <utca>Jókai_utca</utca>
            <házszám>14</házszám>
       </cim>
       <minősítés>A</minősítés>
    </telep>

    <telep TELEP_ID = "3">
        <kapacitás>6</kapacitás>  
        <cim>
            <település>Szeged</település>
            <utca>Szabadság_utca </utca>
            <házszám>23</házszám>
       </cim>
       <minősítés>C</minősítés>
    </telep>

    <telep TELEP_ID = "4">
        <kapacitás>7</kapacitás>  
        <cim>
            <település>Siófok</település>
            <utca>Balaton_utca</utca>
            <házszám>45</házszám>
       </cim>
       <minősítés>A</minősítés>
    </telep>


    <!-- TULAJDONOS-->
    <tulajdonos TUL_ID="1" TUL_TELEP="1" >
        <név>Kis János</név>
        <telszám>067022344555</telszám>
        <adoszam>12345678-1-11</adoszam>
        <bevétel>1500000</bevétel>
    </tulajdonos>

    <tulajdonos TUL_ID="2" TUL_TELEP="2" >
        <név>Cicz Imre</név>
        <telszám>06205678899</telszám>
        <adoszam>18384763-2-24</adoszam>
        <bevétel>1234560</bevétel>
    </tulajdonos>

    <tulajdonos TUL_ID="3" TUL_TELEP="3" >
        <név>Cset Elek</név>
        <telszám>06703452233</telszám>
        <adoszam>12345679-3-13</adoszam>
        <bevétel>1800000</bevétel>
    </tulajdonos>

    <tulajdonos TUL_ID="4" TUL_TELEP="4" >
        <név>Kis Anikó</név>
        <telszám>06304567788</telszám>
        <adoszam>12341236-2-31</adoszam>
        <bevétel>1850000</bevétel>
    </tulajdonos>


    <!-- AUTOK-->
    <autok AUTO_ID="1" AUTO_TELEP="1" >
        <rendszám>PSY-213</rendszám>
        <modell>Jaguar_F-TYPE</modell>
        <alvázszám>JZMMA18P200411817</alvázszám>
        <gyártásiév>2019</gyártásiév>
    </autok>

    <autok AUTO_ID="2" AUTO_TELEP="2" >
        <rendszám>RYZ-022</rendszám>
        <modell>Mercedes_S63_AMG</modell>
        <alvázszám>JZMMA18P201111111</alvázszám>
        <gyártásiév>2020</gyártásiév>
    </autok>

    <autok AUTO_ID="3" AUTO_TELEP="3" >
        <rendszám>SUV-123</rendszám>
        <modell>Volvo_XC-90</modell>
        <alvázszám>KMMMA18P202345234</alvázszám>
        <gyártásiév>2021</gyártásiév>
    </autok>

    <autok AUTO_ID="4" AUTO_TELEP="2" >
        <rendszám>SRY-345</rendszám>
        <modell>Audi_A5</modell>
        <alvázszám>PZMMA18P200434567</alvázszám>
        <gyártásiév>2020</gyártásiév>
    </autok>

    <autok AUTO_ID="5" AUTO_TELEP="4" >
        <rendszám>PSY-234</rendszám>
        <modell>BMW_M5_Competition</modell>
        <alvázszám>KMMMA18P200413259</alvázszám>
        <gyártásiév>2018</gyártásiév>
    </autok>



    <!-- BÉRLŐ-->
    <bérlő BÉRLŐ_ID="1" BÉRLŐ_AUTO="2">
        <név>Diz Elek</név>
        <telszám>06703439988</telszám>
        <email>dizelek@gmail.com</email>
        <jogositvanyszam>CM001001</jogositvanyszam>
    </bérlő>

    <bérlő BÉRLŐ_ID="2" BÉRLŐ_AUTO="3">
        <név>Farkas Piroska</név>
        <telszám>06209876677</telszám>
        <email>piroksa@gfreemail.hu</email>
        <jogositvanyszam>WW001002</jogositvanyszam>
    </bérlő>

    <bérlő BÉRLŐ_ID="3" BÉRLŐ_AUTO="4">
        <név>Feles Elek</név>
        <telszám>06708995544</telszám>
        <email>felelek@gmail.com</email>
        <jogositvanyszam>MM020105</jogositvanyszam>
    </bérlő>

    <bérlő BÉRLŐ_ID="4" BÉRLŐ_AUTO="5">
        <név>Git Áron</név>
        <telszám>06204563322</telszám>
        <email>gitaron@citromail.hu</email>
        <jogositvanyszam>KK011501</jogositvanyszam>
    </bérlő>


    <!-- ALKALMAZOTTAK-->
    <alkalmazott ALK_ID="1" ALK_TELEP="2"> 
        <név>Hideg Ottó</név>
        <beosztás>Adminisztrátor</beosztás>
        <életkor>48</életkor>
        <születésiév>1975</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="2" ALK_TELEP="3"> 
        <név>Kis Eszter</név>
        <beosztás>Üzletvezető</beosztás>
        <életkor>45</életkor>
        <születésiév>1978</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="3" ALK_TELEP="1"> 
        <név>Pat Tamás</név>
        <beosztás>supervisor</beosztás>
        <életkor>35</életkor>
        <születésiév>1988</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="4" ALK_TELEP="4"> 
        <név>Tra Pista</név>
        <beosztás>marketing_manager</beosztás>
        <életkor>39</életkor>
        <születésiév>1984</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="5" ALK_TELEP="2"> 
        <név>Viz Elma</név>
        <beosztás>hr_vezető</beosztás>
        <életkor>45</életkor>
        <születésiév>1978</születésiév>
    </alkalmazott>

    <!-- BONUSZ-->
    <bonusz BONUSZ_ID="1" ALKALMAZOTT_FK = "1" KÉPESÍTÉS_FK="1" >
        <extra>10000</extra>
    </bonusz>

    <bonusz BONUSZ_ID="2" ALKALMAZOTT_FK = "2" KÉPESÍTÉS_FK="2" >
        <extra>25000</extra>
    </bonusz>

    <bonusz BONUSZ_ID="3" ALKALMAZOTT_FK = "3" KÉPESÍTÉS_FK="3" >
        <extra>30000</extra>
    </bonusz>

    <!-- Képesítés-->
    <képesítés KÉPESÍTÉS_ID="1">
     <bizoszítványszám>7245889</bizoszítványszám>
     <év>2021</év>    
     <nyelv>angol</nyelv>
     <tipus>A2</tipus>   
    </képesítés>

    <képesítés KÉPESÍTÉS_ID="2">
        <bizoszítványszám>7245867</bizoszítványszám>
        <év>2015</év>    
        <nyelv>magyar</nyelv>
        <tipus>B2</tipus>    
    </képesítés>

    <képesítés KÉPESÍTÉS_ID="3">
        <bizoszítványszám>7224589</bizoszítványszám>
        <év>2010</év>    
        <nyelv>angol</nyelv>
        <tipus>C1</tipus>   
    </képesítés>

    <képesítés KÉPESÍTÉS_ID="4">
        <bizoszítványszám>7298174</bizoszítványszám>
        <év>2011</év>    
        <nyelv>angol</nyelv>
        <tipus>B1</tipus>  
    </képesítés>




</H2Z4X3_autokolcsonzo>

=== PazmanAndras/H2Z4X3_XMLGyak/XMLTaskH2Z4X3/XMLh2z4x3.xml
<?xml version="1.0" encoding="UTF-8"?>


<H2Z4X3_autokolcsonzo xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="XMLSchemah2z4x3.xsd">
    
    <!-- TELEP -->
    <telep TELEP_ID = "1">
        <kapacitás>5</kapacitás>  
        <cim>
            <település>Budapest</település>
            <utca>Benczúr_utca</utca>
            <házszám>23</házszám>
       </cim>
       <minősítés>B</minősítés>
       <minősítés>A</minősítés>
       <minősítés>A</minősítés>
    </telep>

    <telep TELEP_ID = "2">
        <kapacitás>8</kapacitás>  
        <cim>
            <település>Budapest</település>
            <utca>Jókai_utca</utca>
            <házszám>14</házszám>
       </cim>
       <minősítés>A</minősítés>
       <minősítés>B</minősítés>
       <minősítés>C</minősítés>
    </telep>

    <telep TELEP_ID = "3">
        <kapacitás>6</kapacitás>  
        <cim>
            <település>Szeged</település>
            <utca>Szabadság_utca </utca>
            <házszám>23</házszám>
       </cim>
       <minősítés>C</minősítés>
       <minősítés>A</minősítés>
       <minősítés>B</minősítés>
    </telep>

    <telep TELEP_ID = "4">
        <kapacitás>7</kapacitás>  
        <cim>
            <település>Siófok</település>
            <utca>Balaton_utca</utca>
            <házszám>45</házszám>
       </cim>
       <minősítés>A</minősítés>
       <minősítés>C</minősítés>
       <minősítés>B</minősítés>
    </telep>


    <!-- TULAJDONOS-->
    <tulajdonos TUL_ID="1" TUL_TELEP="1" >
        <név>Kis János</név>
        <telszám>067022344555</telszám>
        <telszám>067022344345</telszám>
        <telszám>067022344897</telszám>
        <adoszam>12345678-1-11</adoszam>
        <bevétel>1500000</bevétel>
    </tulajdonos>

    <tulajdonos TUL_ID="2" TUL_TELEP="2" >
        <név>Cicz Imre</név>
        <telszám>06205678899</telszám>
        <telszám>063022344345</telszám>
        <adoszam>18384763-2-24</adoszam>
        <bevétel>1234560</bevétel>
    </tulajdonos>

    <tulajdonos TUL_ID="3" TUL_TELEP="3" >
        <név>Cset Elek</név>
        <telszám>06703452233</telszám>
        <telszám>06702234367</telszám>
        <telszám>062022344897</telszám>
        <adoszam>12345679-3-13</adoszam>
        <bevétel>1800000</bevétel>
    </tulajdonos>

    <tulajdonos TUL_ID="4" TUL_TELEP="4" >
        <név>Kis Anikó</név>
        <telszám>06304567788</telszám>
        <telszám>06702232233</telszám>
        <adoszam>12341236-2-31</adoszam>
        <bevétel>1850000</bevétel>
    </tulajdonos>


    <!-- AUTOK-->
    <autok AUTO_ID="1" AUTO_TELEP="1" >
        <rendszám>PSY-213</rendszám>
        <modell>Jaguar_F-TYPE</modell>
        <modell>Jaguar_F-TYPE_sport</modell>
        <alvázszám>JZMMA18P200411817</alvázszám>
        <gyártásiév>2019</gyártásiév>
    </autok>

    <autok AUTO_ID="2" AUTO_TELEP="2" >
        <rendszám>RYZ-022</rendszám>
        <modell>Mercedes_S63_AMG</modell>
        <modell>Mercedes_S63_AMG_musclecar</modell>
        <alvázszám>JZMMA18P201111111</alvázszám>
        <gyártásiév>2020</gyártásiév>
    </autok>

    <autok AUTO_ID="3" AUTO_TELEP="3" >
        <rendszám>SUV-123</rendszám>
        <modell>Volvo_XC-90</modell>
        <modell>xc90_suv</modell>
        <alvázszám>KMMMA18P202345234</alvázszám>
        <gyártásiév>2021</gyártásiév>
    </autok>

    <autok AUTO_ID="4" AUTO_TELEP="2" >
        <rendszám>SRY-345</rendszám>
        <modell>Audi_A5</modell>
        <modell>Audi_A5_sedan</modell>
        <alvázszám>PZMMA18P200434567</alvázszám>
        <gyártásiév>2020</gyártásiév>
    </autok>

    <autok AUTO_ID="5" AUTO_TELEP="4" >
        <rendszám>PSY-234</rendszám>
        <modell>BMW_M5_Competition</modell>
        <modell>M5_cabrio</modell>
        <alvázszám>KMMMA18P200413259</alvázszám>
        <gyártásiév>2018</gyártásiév>
    </autok>



    <!-- BÉRLŐ-->
    <bérlő BÉRLŐ_ID="1" BÉRLŐ_AUTO="2">
        <név>Diz Elek</név>
        <telszám>06703439988</telszám>
        <telszám>06304567788</telszám>
        <email>dizelek@gmail.com</email>
        <jogositvanyszam>CM001001</jogositvanyszam>
    </bérlő>

    <bérlő BÉRLŐ_ID="2" BÉRLŐ_AUTO="3">
        <név>Farkas Piroska</név>
        <telszám>06209876677</telszám>
        <telszám>06304567788</telszám>
        <email>piroksa@gfreemail.hu</email>
        <jogositvanyszam>WW001002</jogositvanyszam>
    </bérlő>

    <bérlő BÉRLŐ_ID="3" BÉRLŐ_AUTO="4">
        <név>Feles Elek</név>
        <telszám>06708995544</telszám>
        <telszám>06304567788</telszám>
        <email>felelek@gmail.com</email>
        <jogositvanyszam>MM020105</jogositvanyszam>
    </bérlő>

    <bérlő BÉRLŐ_ID="4" BÉRLŐ_AUTO="5">
        <név>Git Áron</név>
        <telszám>06204563322</telszám>
        <telszám>06708995544</telszám>
        <email>gitaron@citromail.hu</email>
        <jogositvanyszam>KK011501</jogositvanyszam>
    </bérlő>


    <!-- ALKALMAZOTTAK-->
    <alkalmazott ALK_ID="1" ALK_TELEP="2"> 
        <név>Hideg Ottó</név>
        <beosztás>Adminisztrátor</beosztás>
        <beosztás>hr_team_lead</beosztás>
        <beosztás>hr_supervisor</beosztás>
        <életkor>48</életkor>
        <születésiév>1975</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="2" ALK_TELEP="3"> 
        <név>Kis Eszter</név>
        <beosztás>Üzletvezető</beosztás>
        <beosztás>finance_accountant</beosztás>
        <életkor>45</életkor>
        <születésiév>1978</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="3" ALK_TELEP="1"> 
        <név>Pat Tamás</név>
        <beosztás>supervisor</beosztás>
        <beosztás>hr_manager</beosztás>
        <beosztás>facility_manager</beosztás>
        <életkor>35</életkor>
        <születésiév>1988</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="4" ALK_TELEP="4"> 
        <név>Tra Pista</név>
        <beosztás>marketing_manager</beosztás>
        <beosztás>marketing_consultant</beosztás>
        <életkor>39</életkor>
        <születésiév>1984</születésiév>
    </alkalmazott>

    <alkalmazott ALK_ID="5" ALK_TELEP="2"> 
        <név>Viz Elma</név>
        <beosztás>hr_vezető</beosztás>
        <beosztás>hr_administrator</beosztás>
        <életkor>45</életkor>
        <születésiév>1978</születésiév>
    </alkalmazott>

    <!-- BONUSZ-->
    <bonusz BONUSZ_ID="1" ALKALMAZOTT_FK = "1" KÉPESÍTÉS_FK="1" >
        <extra>10000</extra>
    </bonusz>

    <bonusz BONUSZ_ID="2" ALKALMAZOTT_FK = "2" KÉPESÍTÉS_FK="2" >
        <extra>25000</extra>
    </bonusz>

    <bonusz BONUSZ_ID="3" ALKALMAZOTT_FK = "3" KÉPESÍTÉS_FK="3" >
        <extra>30000</extra>
    </bonusz>

    <!-- Képesítés-->
    <képesítés KÉPESÍTÉS_ID="1">
     <bizoszítványszám>7245889</bizoszítványszám>
     <év>2021</év>
     <év>2022</év>   
     <nyelv>angol</nyelv>
     <tipus>A2</tipus>   
    </képesítés>

    <képesítés KÉPESÍTÉS_ID="2">
        <bizoszítványszám>7245867</bizoszítványszám>
        <év>2015</év>
        <év>2011</év>    
        <nyelv>magyar</nyelv>
        <tipus>B2</tipus>    
    </képesítés>

    <képesítés KÉPESÍTÉS_ID="3">
        <bizoszítványszám>7224589</bizoszítványszám>
        <év>2010</év>
        <év>2020</év>     
        <nyelv>angol</nyelv>
        <tipus>C1</tipus>   
    </képesítés>

    <képesítés KÉPESÍTÉS_ID="4">
        <bizoszítványszám>7298174</bizoszítványszám>
        <év>2011</év>
        <év>2013</év> 
        <nyelv>angol</nyelv>
        <tipus>B1</tipus>  
    </képesítés>

</H2Z4X3_autokolcsonzo>
